#!/bin/bash
clang_path="${HOME}/cbl/bin/clang"
gcc_path="${HOME}/cbl/bin/aarch64-linux-gnu-"
gcc_32_path="${HOME}/cbl/bin/arm-linux-gnueabi-"

source=`pwd`
START=$(date +"%s")

date="`date +"%m%d-%H%M"`"

args="-j$(nproc --all) O=out \
	ARCH=arm64 "

print (){
case ${2} in
	"red")
	echo -e "\033[31m $1 \033[0m";;

	"blue")
	echo -e "\033[34m $1 \033[0m";;

	"yellow")
	echo -e "\033[33m $1 \033[0m";;

	"purple")
	echo -e "\033[35m $1 \033[0m";;

	"sky")
	echo -e "\033[36m $1 \033[0m";;

	"green")
	echo -e "\033[32m $1 \033[0m";;

	*)
	echo $1
	;;
	esac
}

args+="CC=$clang_path \
	CLANG_TRIPLE=aarch64-linux-gnu- \
	CROSS_COMPILE=$gcc_path \
	AR=${HOME}/cbl/bin/llvm-ar \
	NM=${HOME}/cbl/bin/llvm-nm \
	OBJCOPY=${HOME}/cbl/bin/llvm-objcopy \
	OBJDUMP=${HOME}/cbl/bin/llvm-objdump \
	STRIP=${HOME}/cbl/bin/llvm-strip \
	CROSS_COMPILE_ARM32=$gcc_32_path "

clean(){
	make mrproper
	make $args mrproper
}

export KBUILD_BUILD_USER="dipper"
export KBUILD_BUILD_HOST="ALKALiKong"

build_dipper(){
	print "Building Li-Kernel..." blue
	make $args li-dipper_defconfig && make $args
	if [ $? -ne 0 ]; then
    print "Error while building for dipper!" red
	else
    export zipname="Li-kernel-$date.zip"
    mkzip
        fi
}

mkzip(){
	cp -f out/arch/arm64/boot/Image.gz-dtb ~/AnyKernel3
	cd ~/AnyKernel3
	make
	mv -f *.zip ~/$zipname
	cd ${HOME}
	cd $source
	print "All done.Find it at ${HOME}/$zipname" green
	sftp_upload
}

sftp_upload(){
cd ${HOME}
lftp <<EOF
    set sftp:auto-confirm yes
    open sftp://${sftp_server}
    user ${sftp_username} ${sftp_pwd}
    cd /home/frs/project/derp-unofficial-dipper
    mkdir ${date}
    cd ${date}
    mput *.zip
    bye
EOF
 
    echo "Sftp uploading done!"
}
	clean
	build_dipper
	
